[build-system]
# Minimum requirements for the build system to execute.
# See https://github.com/scipy/scipy/pull/12940 for the AIX issue.
requires = [
"biopython>=1.79",
"openpyxl>=3.0.9",
"pandas>=1.3.5"
]